
import React, { useState } from 'react';
import { Card, CardContent, CardFooter, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Mail } from 'lucide-react';
import { StudentInfo } from '@/hooks/assessment';

interface TestEntryStepProps {
  onStart: (withEmail: boolean) => void;
  onStudentInfoSubmit: (info: StudentInfo) => void;
}

const TestEntryStep: React.FC<TestEntryStepProps> = ({ 
  onStart,
  onStudentInfoSubmit 
}) => {
  const [emailResults, setEmailResults] = useState(false);
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Save student info if email is enabled
    if (emailResults) {
      onStudentInfoSubmit({
        name,
        email,
        sessionId: ''  // This will be generated by the parent component
      });
    }
    
    onStart(emailResults);
  };

  return (
    <Card className="max-w-lg mx-auto">
      <CardHeader className="text-center">
        <h2 className="text-2xl font-bold text-assessment-blue">Quick Assessment</h2>
        <p className="text-gray-600">Measure your speaking skills in minutes</p>
      </CardHeader>
      
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex items-start space-x-2">
            <Checkbox 
              id="email-results" 
              checked={emailResults} 
              onCheckedChange={(checked) => setEmailResults(checked === true)}
            />
            <div className="grid gap-1.5 leading-none">
              <Label
                htmlFor="email-results"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                ✅ Email me my results
              </Label>
              <p className="text-xs text-muted-foreground">
                Get your detailed assessment report by email
              </p>
            </div>
          </div>
          
          {emailResults && (
            <div className="space-y-3 bg-gray-50 p-3 rounded-md">
              <div className="space-y-1">
                <Label htmlFor="name">Name</Label>
                <Input
                  id="name"
                  placeholder="Your name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
              
              <div className="space-y-1">
                <Label htmlFor="email">Email</Label>
                <div className="flex space-x-2">
                  <div className="relative flex-1">
                    <Mail className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input
                      id="email"
                      type="email"
                      placeholder="your.email@example.com"
                      className="pl-8"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      required={emailResults}
                    />
                  </div>
                </div>
              </div>
            </div>
          )}
          
          <Button type="submit" className="w-full mt-4">
            Continue to Quick Assessment
          </Button>
        </form>
      </CardContent>
      
      <CardFooter className="justify-between text-xs text-muted-foreground">
        <div>10 minutes or less</div>
        <div>CEFR level evaluation</div>
      </CardFooter>
    </Card>
  );
};

export default TestEntryStep;
